---
# tasks file for docker-artifactory

# https://github.com/JFrogDev/artifactory-docker-examples/tree/master/docker-compose

- name: create group
  become: yes
  group:
    name: artifactory
    gid: 1030
    state: present

- name: create user
  become: yes
  user:
    name: artifactory
    groups: artifactory,wheel
    uid: 1030
    shell: /bin/bash
    generate_ssh_key: yes
    ssh_key_bits: 4096
    password: "{{ vaulted_docker_artifactory_artifactory_user_password | password_hash('sha512') }}"

- name: create the artifactory folders
  become: yes
  file:
    path: "{{ docker_artifactory_data }}/{{ item }}"
    state: directory
    mode: 0755
    owner: artifactory
    group: artifactory
    recurse: yes
  with_items:
    - artifactory
    - artifactory/etc/plugins
    - artifactory/access
    - artifactory/backup
    - artifactory/data
    - artifactory/logs
  notify: "restart nginx"

- name: create the artifactory_dockerfile folder
  become: yes
  file:
    path: "{{ docker_artifactory_data }}/artifactory_dockerfile/certs/"
    state: directory
    mode: 0740
    recurse: yes

- name: copy the artifactory license
  become: yes
  copy:
    src: artifactory.lic
    dest: "{{ docker_artifactory_data }}/artifactory/etc/"
    mode: 0400
    owner: artifactory
    group: artifactory

- name: copy the artifactory plugins
  become: yes
  copy:
    src: "{{ item }}"
    dest: "{{ docker_artifactory_data }}/artifactory/etc/plugins/"
    mode: 0755
    owner: artifactory
    group: artifactory
  with_fileglob:
    - "files/plugins/*"

  # By default, everything in the file is commented out, so doing an overwrite is okay.
- name: copy the artifactory system properties file
  become: yes
  copy:
    src: files/artifactory.system.properties
    dest: "{{ docker_artifactory_data }}/artifactory/etc/"
    mode: 0400
    owner: artifactory
    group: artifactory

- name: create the nginx folders
  become: yes
  file:
    path: "{{ docker_artifactory_data }}/{{ item }}"
    state: directory
    mode: 0700
    owner: root
    group: root
    recurse: yes
  with_items:
    - nginx/conf.d
    - nginx/logs
    - nginx/ssl/artifactory
  notify: "restart nginx"

- name: copy the nginx conf
  # The conf file was generated by using the reverse proxy generator inside Artifactory (Admin tab, Configuration | Reverse Proxy).
  become: yes
  template:
    src: artifactory.conf.j2
    dest: "{{ docker_artifactory_data }}/nginx/conf.d/artifactory.conf"
    owner: root
    group: root
    mode: 0400
  notify: "restart nginx"

- name: copy the key
  become: yes
  copy:
    src: "files/{{ docker_artifactory_dns }}.key"
    dest: "{{ docker_artifactory_data }}/nginx/ssl/artifactory/{{ docker_artifactory_dns }}.key"

- name: own the key
  become: yes
  file:
    path: "{{ docker_artifactory_data }}/nginx/ssl/artifactory/{{ docker_artifactory_dns }}.key"
    state: file
    group: root
    owner: root
    mode: 0400

- name: copy the pem
  become: yes
  copy:
    src: "files/{{ docker_artifactory_dns }}.pem"
    dest: "{{ docker_artifactory_data }}/nginx/ssl/artifactory/{{ docker_artifactory_dns }}.pem"

- name: own the pem
  become: yes
  file:
    path: "{{ docker_artifactory_data }}/nginx/ssl/artifactory/{{ docker_artifactory_dns }}.pem"
    state: file
    group: root
    owner: root
    mode: 0400

- name: create the postgres folders
  become: yes
  file:
    path: "{{ docker_artifactory_data }}/postgresql"
    state: directory
    mode: 0700
  notify: "restart nginx"

- name: pull the postgres docker image
  become: yes
  docker_image:
    name: postgres:{{ docker_artifactory_postgresql_tag }}
    source: pull
  notify: "restart artifactory"

- name: pull the artifactory-pro docker image
  become: yes
  docker_image:
    name: docker.bintray.io/jfrog/artifactory-pro:{{ docker_artifactory_artifactory_pro_tag }}
    source: pull
  notify: "restart nginx"

- name: copy custom certificates to trust
  become: yes
  copy:
    src: "{{ item.path }}"
    dest: "{{ docker_artifactory_data }}/artifactory_dockerfile/certs/"
    remote_src: "{{ item.remote_src }}"
    mode: 0744
    owner: root
    group: root
  loop: "{{ docker_artifactory_certs_to_trust }}"
  when: docker_artifactory_certs_to_trust is defined

- name: copy the artifactory dockerfile
  become: yes
  template:
    src: "templates/Dockerfile"
    dest: "{{ docker_artifactory_data }}/artifactory_dockerfile/Dockerfile"
    mode: 0700
    owner: root
    group: root

- name: build the artifactory image
  become: yes
  docker_image:
    build:
      path: "{{ docker_artifactory_data }}/artifactory_dockerfile"
      pull: no
    name: artifactory/artifactory-pro-custom
    tag: "{{ docker_artifactory_artifactory_pro_tag }}"
    source: build

- name: pull the nginx docker image
  become: yes
  docker_image:
    name: nginx:{{ docker_artifactory_nginx_tag }}
    source: pull

- name: create the docker_compose folder
  become: yes
  file:
    path: "{{ docker_artifactory_docker_compose_folder }}"
    state: directory
    mode: 0740
    recurse: yes

- name: copy the docker-compose.yml file
  become: yes
  template:
    src: "templates/docker-compose.yml"
    dest: "{{ docker_artifactory_docker_compose_folder }}/docker-compose.yml"
    mode: 0700
    owner: root
    group: root

- name: run the postgres export and import
  include_tasks: postgresql_data_export_import.yml
  when: docker_artifactory_postgresql_data_export_import | bool

- name: bring up the docker instances for artifactory, nginx, and postgresql
  become: yes
  docker_compose:
    project_name: artifactory
    project_src: "{{ docker_artifactory_docker_compose_folder }}"
  register: docker_compose_output

- assert:
    that:
      - "docker_compose_output.ansible_facts.postgresql.postgresql.state.running"
      - "docker_compose_output.ansible_facts.artifactory.artifactory.state.running"
      - "docker_compose_output.ansible_facts.nginx.nginx.state.running"

- name: delete the docker-compose as it has secrets
  become: yes
  file:
    path: "{{ docker_artifactory_docker_compose_folder }}"
    state: absent